# Generated by Django 5.2.7 on 2025-10-28 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parcela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('cultivo', models.CharField(blank=True, max_length=120)),
                ('superficie_ha', models.DecimalField(decimal_places=2, help_text='Hectáreas', max_digits=7)),
                ('lat', models.DecimalField(decimal_places=6, help_text='Latitud WGS84', max_digits=9)),
                ('lon', models.DecimalField(decimal_places=6, help_text='Longitud WGS84', max_digits=9)),
                ('descripcion', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['nombre'],
                'indexes': [models.Index(fields=['nombre'], name='parcelas_pa_nombre_6ed3f0_idx')],
            },
        ),
    ]
