# Generated by Django 5.2.7 on 2025-10-29 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcelas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=80, unique=True)),
                ('tipo', models.CharField(choices=[('humedad_suelo', 'Humedad de suelo'), ('temperatura', 'Temperatura'), ('caudal', 'Caudal'), ('ph', 'pH'), ('conductividad', 'Conductividad')], max_length=32)),
                ('unidad', models.CharField(blank=True, help_text='Ej.: %, °C, L/min', max_length=16)),
                ('intervalo_seg', models.PositiveIntegerField(default=900, help_text='Frecuencia esperada de muestreo')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('mantenimiento', 'Mantenimiento')], default='activo', max_length=16)),
                ('ultima_lectura_valor', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('ultima_lectura_ts', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('parcela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensores', to='parcelas.parcela')),
            ],
            options={
                'ordering': ['parcela__nombre', 'codigo'],
                'indexes': [models.Index(fields=['codigo'], name='parcelas_se_codigo_e6dc54_idx'), models.Index(fields=['tipo'], name='parcelas_se_tipo_272c6d_idx')],
            },
        ),
    ]
